# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/sync_project/project_1/project_1.srcs/sources_1/ip/mult_32x32/mult_32x32.xci
# IP: The module: 'mult_32x32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/sync_project/project_1/project_1.srcs/sources_1/ip/mult_32x32/mult_32x32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_32x32'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: E:/sync_project/project_1/project_1.srcs/sources_1/ip/mult_32x32/mult_32x32.xci
# IP: The module: 'mult_32x32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/sync_project/project_1/project_1.srcs/sources_1/ip/mult_32x32/mult_32x32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mult_32x32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
