# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/sync_project/project_1/project_1.srcs/sources_1/ip/walshtable/walshtable.xci
# IP: The module: 'walshtable' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/sync_project/project_1/project_1.srcs/sources_1/ip/walshtable/walshtable_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'walshtable'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: E:/sync_project/project_1/project_1.srcs/sources_1/ip/walshtable/walshtable.xci
# IP: The module: 'walshtable' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/sync_project/project_1/project_1.srcs/sources_1/ip/walshtable/walshtable_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'walshtable'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
