# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/sync_project/project_1/project_1.srcs/sources_1/ip/ram_2port_0/ram_2port_0.xci
# IP: The module: 'ram_2port_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/sync_project/project_1/project_1.srcs/sources_1/ip/ram_2port_0/ram_2port_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_2port_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: E:/sync_project/project_1/project_1.srcs/sources_1/ip/ram_2port_0/ram_2port_0.xci
# IP: The module: 'ram_2port_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/sync_project/project_1/project_1.srcs/sources_1/ip/ram_2port_0/ram_2port_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_2port_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
